In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("class_imbalance_refactored/dataset_865_analcatdata_neavote.csv")
df

    favorable  party_i  party_r  target
0         1.0      0.0      1.0       0
1         1.0      0.0      1.0       0
2         2.0      0.0      1.0       0
3         2.0      0.0      1.0       0
4         2.0      0.0      1.0       1
..        ...      ...      ...     ...
95       10.0      0.0      0.0       0
96       10.0      0.0      0.0       0
97       10.0      0.0      0.0       0
98        1.0      0.0      1.0       0
99        1.0      0.0      1.0       0

[100 rows x 4 columns]

In [3]:
split_idx = 80

df.head()

   favorable  party_i  party_r  target
0        1.0      0.0      1.0       0
1        1.0      0.0      1.0       0
2        2.0      0.0      1.0       0
3        2.0      0.0      1.0       0
4        2.0      0.0      1.0       1

In [12]:
y = df["target"]

X = df.drop(columns=["target"])

X_train = X.head(80).values.astype(float)
X_test = X.tail(20).values.astype(float)

y_train = y.head(80).values.astype(float)
y_test = y.tail(20).values.astype(float)

In [13]:
from logistic_regression import gradient_descent

weight, bias = gradient_descent(X_train, y_train)

print(weight, bias)

[-0.56755779 -0.03866146 -0.26260682] -0.34230053242468284

In [19]:
from logistic_regression import predict

y_pred = predict(X_test, weight, bias)

In [23]:
from metrics import confusion_matrix

matrix = confusion_matrix(y_pred, y_test)
matrix

array([[ 0,  0],
       [ 1, 19]])

In [27]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])